image:
  file: .gitpod.Dockerfile
tasks:
- command: "cargo test"
- command: "cargo watch -x check"
  openIn: right
  openMode: tab-before

vscode:
  extensions:
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
