image:
  file: .gitpod/Dockerfile

tasks:
- command: "cargo test"
- command: "cargo watch -x check"
  openIn: right
  openMode: tab-before

vscode:
  extensions:
  - bungcip.better-toml
  - matklad.rust-analyzer
